
package appsiux;

import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import java.util.regex.Matcher;//validar correo
import java.util.regex.Pattern;//validar correo
import static javax.swing.JOptionPane.ERROR_MESSAGE;


public class VerAlumnos extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;
    /**
     * Creates new form VerAlumnos
     */
    
    int seleccionAlum = -1;
    static AlumnoListModel ModelAlumnos = new AlumnoListModel();
    
    int seleccion;
    MateriaListModel materias; // listMateria del constructor
    
    Ventana v;

    public VerAlumnos(MateriaListModel listMateria, AlumnoListModel ModelAlumnos, Ventana v) {
        this.materias = listMateria;
        this.ModelAlumnos = ModelAlumnos;
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setTitle("Alumnos");
        this.v = v;
    
        listAlumno.setModel(ModelAlumnos);
        
        //inicializamos los mensajes de campo obligatorio como no visibles
        obligatorio1.setVisible(false);
        obligatorio2.setVisible(false);
        obligatorio3.setVisible(false);
        obligatorio4.setVisible(false);
        obligatorio5.setVisible(false);
        obligatorio6.setVisible(false);
        labelVerificar.setVisible(false);
        labelVerificar2.setVisible(false);

    }

    public VerAlumnos() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setTitle("Alumnos");
        listAlumno.setModel(ModelAlumnos);
        obligatorio1.setVisible(false);
        obligatorio2.setVisible(false);
        obligatorio3.setVisible(false);
        obligatorio4.setVisible(false);
        obligatorio5.setVisible(false);
        obligatorio6.setVisible(false);
        labelVerificar.setVisible(false);
    }
   
    int contador = 0;
   //Metodo para validar si un campo esta vacio
    public void campoObligatorio() {
         String email;
         // Patrón para validar el email
        Pattern pattern = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                        + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
        // El email a validar
        email = txtCorreo.getText();
        Matcher mather = pattern.matcher(email);
        if (txtNombreAlumno.getText().isEmpty()) {
            obligatorio1.setVisible(true);
            contador++;
        } else {
            obligatorio1.setVisible(false);
        }
        if (txtApellidoPaterno.getText().isEmpty()) {
            obligatorio2.setVisible(true);
            contador++;
        } else {
            obligatorio2.setVisible(false);
        }
        if (txtApellidoMaterno.getText().isEmpty()) {
            obligatorio3.setVisible(true);
            contador++;
        } else {
            obligatorio3.setVisible(false);
        }
        if (txtCorreo.getText().isEmpty()) {
            obligatorio4.setVisible(true);
            contador++;
        } else {
            obligatorio4.setVisible(false);
        }
        if (txtIdAlumno.getText().isEmpty()) {
            obligatorio5.setVisible(true);
            contador++;
        } else {
            obligatorio5.setVisible(false);
        }
        if (txtEdad.getText().isEmpty()) {
            obligatorio6.setVisible(true);
            contador++;
        } else {
            obligatorio6.setVisible(false);
        } if (mather.find() == true){
            labelVerificar.setVisible(true);
        }else{contador++; //Validamos el correo
            JOptionPane.showMessageDialog(null, "Introduce un correo electrónico válido","Error",ERROR_MESSAGE);}
        
         String validarId = txtIdAlumno.getText();
    for (Alumno alumno : ModelAlumnos.getListAlumno()) {
        if (alumno.getId().equals(validarId)) {
             contador++;
             labelVerificar2.setVisible(false);
            JOptionPane.showMessageDialog(null, "El ID ingresado ya está en uso", "Error",ERROR_MESSAGE);
           break;
        }else{
            labelVerificar2.setVisible(true);
        }
    }
      
            

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listAlumno = new javax.swing.JList<>();
        cbxModificar = new javax.swing.JComboBox<>();
        buttonAltas = new javax.swing.JButton();
        buttonModificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNombreAlumno = new javax.swing.JTextField();
        obligatorio1 = new javax.swing.JLabel();
        txtApellidoPaterno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        obligatorio2 = new javax.swing.JLabel();
        txtApellidoMaterno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        obligatorio3 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        obligatorio4 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIdAlumno = new javax.swing.JTextField();
        obligatorio5 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        obligatorio6 = new javax.swing.JLabel();
        buttonEliminarAlumno = new javax.swing.JButton();
        buttonAgregarAlumno = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelVerificar = new javax.swing.JLabel();
        buttonLimpiar = new javax.swing.JButton();
        labelVerificar2 = new javax.swing.JLabel();
        buttonGenID = new javax.swing.JButton();
        labelBack = new javax.swing.JLabel();

        jLabel14.setText("jLabel14");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(listAlumno);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 267, 230));

        cbxModificar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "Apellido Paterno", "Apellido Materno", "Correo", "ID", "Edad" }));
        cbxModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxModificarActionPerformed(evt);
            }
        });
        getContentPane().add(cbxModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, 30));

        buttonAltas.setText("Altas y bajas");
        buttonAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAltasActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAltas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 270, -1));

        buttonModificar.setText("Modificar ");
        buttonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModificarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 130, 30));

        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 25, -1, -1));

        txtNombreAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreAlumnoActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombreAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 21, 126, -1));

        obligatorio1.setText("Campo obligatorio.");
        getContentPane().add(obligatorio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 51, 116, -1));

        txtApellidoPaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoPaternoActionPerformed(evt);
            }
        });
        getContentPane().add(txtApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 73, 126, -1));

        jLabel2.setText("Apellido Paterno:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 77, -1, -1));

        obligatorio2.setText("Campo obligatorio.");
        getContentPane().add(obligatorio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 103, -1, -1));

        txtApellidoMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoMaternoActionPerformed(evt);
            }
        });
        getContentPane().add(txtApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 125, 126, -1));

        jLabel3.setText("Apellido Materno:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 129, -1, -1));

        obligatorio3.setText("Campo obligatorio.");
        getContentPane().add(obligatorio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 155, -1, -1));

        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 177, 126, -1));

        jLabel5.setText("Correo:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 181, -1, -1));

        obligatorio4.setText("Campo obligatorio.");
        getContentPane().add(obligatorio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 207, 140, -1));

        jLabel4.setText("ID:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 233, -1, -1));

        txtIdAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdAlumnoActionPerformed(evt);
            }
        });
        getContentPane().add(txtIdAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 229, 126, -1));

        obligatorio5.setText("Campo obligatorio.");
        getContentPane().add(obligatorio5, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 259, -1, -1));

        txtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadActionPerformed(evt);
            }
        });
        txtEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEdadKeyTyped(evt);
            }
        });
        getContentPane().add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 287, 30, -1));

        jLabel6.setText("Edad:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 289, -1, -1));

        obligatorio6.setText("Campo obligatorio.");
        getContentPane().add(obligatorio6, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 313, 140, -1));

        buttonEliminarAlumno.setText("Eliminar alumno");
        buttonEliminarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEliminarAlumnoActionPerformed(evt);
            }
        });
        getContentPane().add(buttonEliminarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, -1, -1));

        buttonAgregarAlumno.setText("Agregar alumno");
        buttonAgregarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAgregarAlumnoActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAgregarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, -1, -1));

        jLabel9.setText("Seleccione el alumno  y el atributo a modificar:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 267, -1));

        jLabel7.setText("Alumnos");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        labelVerificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1477903427_sign-check.png"))); // NOI18N
        getContentPane().add(labelVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, -1, -1));

        buttonLimpiar.setText("Limpiar");
        buttonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 90, -1));

        labelVerificar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1477903427_sign-check.png"))); // NOI18N
        getContentPane().add(labelVerificar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, -1, 20));

        buttonGenID.setText("Generar ID");
        buttonGenID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGenIDActionPerformed(evt);
            }
        });
        getContentPane().add(buttonGenID, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, -1, -1));

        labelBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondoVentana4.jpg"))); // NOI18N
        labelBack.setText("jLabel8");
        getContentPane().add(labelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAltasActionPerformed
        seleccionAlum = listAlumno.getSelectedIndex();
        if (seleccionAlum != -1) {
            AltaAlumnos alta = new AltaAlumnos(seleccionAlum, materias, ModelAlumnos);
            alta.setVisible(true);
        }
    }//GEN-LAST:event_buttonAltasActionPerformed

    private void buttonEliminarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEliminarAlumnoActionPerformed
        seleccionAlum = listAlumno.getSelectedIndex();

        if (seleccionAlum != -1) {
            ModelAlumnos.eliminarAlumno(seleccionAlum);
        }
    }//GEN-LAST:event_buttonEliminarAlumnoActionPerformed

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
           
    }//GEN-LAST:event_txtEdadActionPerformed

    private void buttonAgregarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAgregarAlumnoActionPerformed
       
        contador = 0;
       
        campoObligatorio(); // cada vez que falte un campo, se le sumara 1 al contador
        
        if (contador == 0) { // si ningun campo falta el contador valdra 0, entonces podra agregarse el alumno
           
            Alumno a = new Alumno(txtIdAlumno.getText(), txtNombreAlumno.getText(), txtApellidoPaterno.getText(), txtApellidoMaterno.getText(),
                    txtCorreo.getText(), Integer.parseInt(txtEdad.getText()));
            
            ModelAlumnos.addAlumno(a);
            v.setN(v.getN());
            txtIdAlumno.setText("0034"+(v.getN()));
           
        }
    }//GEN-LAST:event_buttonAgregarAlumnoActionPerformed

    private void cbxModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxModificarActionPerformed

    }//GEN-LAST:event_cbxModificarActionPerformed

    private void buttonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModificarActionPerformed
        int alumSeleccion;
        int opcion;
        alumSeleccion = listAlumno.getSelectedIndex(); //opcion seleccionada en el JList alumno
        opcion = cbxModificar.getSelectedIndex(); // opcion seleccionada en el ComboBox desplegable
        if (alumSeleccion!= -1){
            
        ModelAlumnos.actualizarAlumno(opcion, alumSeleccion);
        }
    }//GEN-LAST:event_buttonModificarActionPerformed

    private void txtApellidoMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoMaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoMaternoActionPerformed

    private void txtApellidoPaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoPaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoPaternoActionPerformed

    private void txtNombreAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreAlumnoActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtIdAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdAlumnoActionPerformed

    private void buttonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimpiarActionPerformed
       txtNombreAlumno.setText(" "); txtApellidoPaterno.setText(" ");txtApellidoMaterno.setText(" "); txtCorreo.setText(" ");
            txtEdad.setText(" ");
    }//GEN-LAST:event_buttonLimpiarActionPerformed

    private void txtEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadKeyTyped
        char validar = evt.getKeyChar(); 
            if(Character.isLetter(validar)){
                getToolkit().beep();
                evt.consume();
            
            JOptionPane.showMessageDialog(null, "Ingresar solo números", "Error", JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_txtEdadKeyTyped

    private void buttonGenIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGenIDActionPerformed
        txtIdAlumno.setText("0034"+(v.getN()));
    }//GEN-LAST:event_buttonGenIDActionPerformed

    public JFormattedTextField getTxtEdad() {
        return txtEdad;
    }

    public void setTxtEdad(JFormattedTextField txtEdad) {
        this.txtEdad = txtEdad;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerAlumnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAgregarAlumno;
    private javax.swing.JButton buttonAltas;
    private javax.swing.JButton buttonEliminarAlumno;
    private javax.swing.JButton buttonGenID;
    private javax.swing.JButton buttonLimpiar;
    private javax.swing.JButton buttonModificar;
    private javax.swing.JComboBox<String> cbxModificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelBack;
    private javax.swing.JLabel labelVerificar;
    private javax.swing.JLabel labelVerificar2;
    private javax.swing.JList<String> listAlumno;
    private javax.swing.JLabel obligatorio1;
    private javax.swing.JLabel obligatorio2;
    private javax.swing.JLabel obligatorio3;
    private javax.swing.JLabel obligatorio4;
    private javax.swing.JLabel obligatorio5;
    private javax.swing.JLabel obligatorio6;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtApellidoPaterno;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JFormattedTextField txtEdad;
    private javax.swing.JTextField txtIdAlumno;
    private javax.swing.JTextField txtNombreAlumno;
    // End of variables declaration//GEN-END:variables
}
