
package appsiux;
import javax.swing.JList;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.JTextField;
import javax.swing.WindowConstants;



public class VerMaterias extends javax.swing.JFrame {
    Ventana v;
    private static final long serialVersionUID = 1L;
    /**
     * Creates new form VerMaterias
     */
    static MateriaListModel MateriasModel = new MateriaListModel();
    public VerMaterias(MateriaListModel MateriasModel,Ventana v) {
        initComponents();
        this.v = v;
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Materias");
        setDefaultCloseOperation (WindowConstants.DISPOSE_ON_CLOSE);
        this.MateriasModel = MateriasModel;
        listMateria.setModel(MateriasModel);
        obligatorio1.setVisible(false); //inicializamos los label "Campo obligatorio" como no visibles
        obligatorio2.setVisible(false);
    }
   
    public VerMaterias() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("APP SIU");
         setDefaultCloseOperation (WindowConstants.DISPOSE_ON_CLOSE);
        listMateria.setModel(MateriasModel);
    }
    int contador = 0;
    public void verificar(){
        if(txtNombreMateria.getText().isEmpty()){obligatorio1.setVisible(true);contador++;}else{
        obligatorio1.setVisible(false);}
         if(txtIdMateria.getText().isEmpty()){obligatorio2.setVisible(true);contador++;}else{
        obligatorio2.setVisible(false);}
        String validarId = txtIdMateria.getText();
    for (Materia m : MateriasModel.getListMateria()) {
        if (m.getId().equals(validarId)) {
             contador++;
            JOptionPane.showMessageDialog(null, "El ID ingresado ya está en uso", "Error",ERROR_MESSAGE);
           break;
        }
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listMateria = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreMateria = new javax.swing.JTextField();
        txtIdMateria = new javax.swing.JTextField();
        buttonAddMateria = new javax.swing.JButton();
        buttonEliminarMateria = new javax.swing.JButton();
        buttonModificar = new javax.swing.JButton();
        buttonVerMateria = new javax.swing.JButton();
        buttonGenID = new javax.swing.JButton();
        obligatorio1 = new javax.swing.JLabel();
        obligatorio2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(430, 282));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listMateria.setMaximumSize(new java.awt.Dimension(80, 60));
        listMateria.setPreferredSize(new java.awt.Dimension(80, 60));
        jScrollPane1.setViewportView(listMateria);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 32, 150, 140));

        jLabel1.setText("Materia");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 4, -1, -1));

        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 36, -1, -1));

        jLabel3.setText("ID:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 83, -1, -1));

        txtNombreMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreMateriaActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombreMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 32, 130, -1));

        txtIdMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdMateriaActionPerformed(evt);
            }
        });
        getContentPane().add(txtIdMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 79, 130, -1));

        buttonAddMateria.setText("Agregar Materia");
        buttonAddMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddMateriaActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAddMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 136, -1));

        buttonEliminarMateria.setText("Eliminar Materia");
        buttonEliminarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEliminarMateriaActionPerformed(evt);
            }
        });
        getContentPane().add(buttonEliminarMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 136, -1));

        buttonModificar.setText("Modificar datos");
        buttonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModificarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 144, -1));

        buttonVerMateria.setText("Ver materia");
        buttonVerMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVerMateriaActionPerformed(evt);
            }
        });
        getContentPane().add(buttonVerMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 144, -1));

        buttonGenID.setText("Generar ID");
        buttonGenID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGenIDActionPerformed(evt);
            }
        });
        getContentPane().add(buttonGenID, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        obligatorio1.setText("Campo obligatorio.");
        getContentPane().add(obligatorio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 57, 111, -1));

        obligatorio2.setText("Campo obligatorio.");
        getContentPane().add(obligatorio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 106, 111, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondoVentana4.jpg"))); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(430, 282));
        jLabel4.setMinimumSize(new java.awt.Dimension(430, 282));
        jLabel4.setPreferredSize(new java.awt.Dimension(430, 282));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents
//BOTON ELIMINAR MATERIA
     public int seleccion;
    private void buttonEliminarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEliminarMateriaActionPerformed
     seleccion = listMateria.getSelectedIndex();
        if (seleccion!=-1) {
        MateriasModel.eliminarMateria(seleccion);
        }
    }//GEN-LAST:event_buttonEliminarMateriaActionPerformed
//BOTON AGREGAR MATERIA
    private void buttonAddMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddMateriaActionPerformed
        contador = 0;
        verificar();
        if (contador == 0){
        
        Materia m = new Materia(txtNombreMateria.getText(), txtIdMateria.getText());
        MateriasModel.addMateria(m);
         v.setO(v.getO());
        txtIdMateria.setText("0014"+(v.getO()));
        }
    }//GEN-LAST:event_buttonAddMateriaActionPerformed


    private void buttonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModificarActionPerformed
       seleccion = listMateria.getSelectedIndex();
       if(seleccion != -1){
       String[] options = {"Nombre", "ID"};
       int selec = JOptionPane.showOptionDialog(null, "Seleccione el atributo a modificar",
       "Modificar", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,null, options, options[0]);
   
       MateriasModel.actualizarMateria(seleccion, selec);
        }else{
        JOptionPane.showMessageDialog(null, "Selecciona una materia", "Modificar datos", JOptionPane.WARNING_MESSAGE);
       }
        
    }//GEN-LAST:event_buttonModificarActionPerformed

    private void txtIdMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdMateriaActionPerformed

    private void txtNombreMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreMateriaActionPerformed

    private void buttonVerMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVerMateriaActionPerformed
       seleccion = listMateria.getSelectedIndex();
       if(seleccion != -1){
           TablaMateria tablamateria = new TablaMateria(MateriasModel, seleccion);
           tablamateria.setVisible(true);
           
       }
    }//GEN-LAST:event_buttonVerMateriaActionPerformed

    private void buttonGenIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGenIDActionPerformed
    txtIdMateria.setText("0014"+(v.getO()));
 
    }//GEN-LAST:event_buttonGenIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerMaterias().setVisible(true);
            }
        });
    }

    public JList<String> getListMateria() {
        return listMateria;
    }

    public void setListMateria(JList<String> listMateria) {
        this.listMateria = listMateria;
    }

    public MateriaListModel getMateriasModel() {
        return MateriasModel;
    }

    public void setMateriasModel(MateriaListModel list_model) {
        VerMaterias.MateriasModel = list_model;
    }

    public JTextField getTxtIdMateria() {
        return txtIdMateria;
    }

    public void setTxtIdMateria(JTextField txtIdMateria) {
        this.txtIdMateria = txtIdMateria;
    }

    public JTextField getTxtNombreMateria() {
        return txtNombreMateria;
    }

    public void setTxtNombreMateria(JTextField txtNombreMateria) {
        this.txtNombreMateria = txtNombreMateria;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddMateria;
    private javax.swing.JButton buttonEliminarMateria;
    private javax.swing.JButton buttonGenID;
    private javax.swing.JButton buttonModificar;
    private javax.swing.JButton buttonVerMateria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listMateria;
    private javax.swing.JLabel obligatorio1;
    private javax.swing.JLabel obligatorio2;
    private javax.swing.JTextField txtIdMateria;
    private javax.swing.JTextField txtNombreMateria;
    // End of variables declaration//GEN-END:variables
}
