
package appsiux;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.WindowConstants;


public class VerProfesores extends javax.swing.JFrame {

    /**
     * Creates new form VerProfesores
     */
    static ProfesorListModel list_model = new ProfesorListModel();
    javax.swing.JList<String> listMateria;
    MateriaListModel materias;
    int seleccionProf = -1;
    int seleccion;
    int n =0;
    Ventana v;
    public VerProfesores(MateriaListModel listMateria, ProfesorListModel list_model, Ventana v) {
        initComponents();
        this.v = v;
        this.seleccion = seleccion;
        this.materias = listMateria;
        this.list_model = list_model;
        setLocationRelativeTo(null);
        setDefaultCloseOperation (WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setTitle("Profesores");
        //list_model = materias.getMateria(seleccion).profesor; //model list profesor en la clase Materia
        listProfesor.setModel(list_model);
        
        //inicializamos los mensajes de campo obligatorio como no visibles
        obligatorio1.setVisible(false);
        obligatorio2.setVisible(false);
        obligatorio3.setVisible(false);
        obligatorio4.setVisible(false);
        obligatorio5.setVisible(false);
        obligatorio6.setVisible(false);
        labelVerificar.setVisible(false);
        labelVerificar3.setVisible(false);
    }
    public VerProfesores() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation (WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setTitle("Profesores");
        obligatorio1.setVisible(false);
        obligatorio2.setVisible(false);
        obligatorio3.setVisible(false);
        obligatorio4.setVisible(false);
        obligatorio5.setVisible(false);
        obligatorio6.setVisible(false);
        labelVerificar.setVisible(false);
    }
    int contador = 0;
    public void campoObligatorio(){
        String email;
         // Patrón para validar el email
        Pattern pattern = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                        + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
        // El email a validar
        email = txtCorreo.getText();
        Matcher mather = pattern.matcher(email);

        if(txtNombreProfesor.getText().isEmpty()){obligatorio1.setVisible(true);contador++;}else{
        obligatorio1.setVisible(false);}
         if(txtApellidoPaterno.getText().isEmpty()){obligatorio2.setVisible(true);contador++;}else{
        obligatorio2.setVisible(false);}
          if(txtApellidoMaterno.getText().isEmpty()){obligatorio3.setVisible(true);contador++;}else{
        obligatorio3.setVisible(false);}
           if(txtIdProfesor.getText().isEmpty()){obligatorio4.setVisible(true);contador++;}else{
        obligatorio4.setVisible(false);}
            if(txtCorreo.getText().isEmpty()){obligatorio5.setVisible(true);contador++;}else{     
        obligatorio5.setVisible(false);}
             if(txtTitulo.getText().isEmpty()){obligatorio6.setVisible(true);contador++;}else{
        obligatorio6.setVisible(false);}
              if (mather.find() == true){labelVerificar.setVisible(true);}else{contador++;
              JOptionPane.showMessageDialog(null, "Introduce un correo electrónico válido","Error",ERROR_MESSAGE);}
              String validarId = txtIdProfesor.getText();
    for (Profesor profesor : list_model.getProfesorList()) {
        if (profesor.getId().equals(validarId)) {
             contador++;
              labelVerificar3.setVisible(false);
            JOptionPane.showMessageDialog(null, "El ID ingresado ya está en uso", "Error",ERROR_MESSAGE);
           break;
        }else{
             labelVerificar3.setVisible(true);
        }
    }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelVerificar2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listProfesor = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombreProfesor = new javax.swing.JTextField();
        txtApellidoPaterno = new javax.swing.JTextField();
        txtApellidoMaterno = new javax.swing.JTextField();
        txtIdProfesor = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        buttonModificarProfesor = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cbxModificar = new javax.swing.JComboBox<>();
        obligatorio1 = new javax.swing.JLabel();
        obligatorio2 = new javax.swing.JLabel();
        obligatorio3 = new javax.swing.JLabel();
        obligatorio4 = new javax.swing.JLabel();
        obligatorio5 = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        obligatorio6 = new javax.swing.JLabel();
        buttonAltas = new javax.swing.JButton();
        labelVerificar = new javax.swing.JLabel();
        buttonAddProfesor = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        labelVerificar3 = new javax.swing.JLabel();
        buttonEliminarProfesor = new javax.swing.JButton();
        buttonGenID = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelVerificar2.setBackground(new java.awt.Color(255, 255, 255));
        labelVerificar2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(listProfesor);

        labelVerificar2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 40, 214, 210));

        jLabel1.setText("Nombre:");
        labelVerificar2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 44, -1, -1));

        jLabel2.setText("Apellido paterno:");
        labelVerificar2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 92, -1, -1));

        jLabel3.setText("Apellido materno:");
        labelVerificar2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 140, -1, -1));

        jLabel4.setText("ID:");
        labelVerificar2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 182, -1, -1));

        jLabel5.setText("Correo:");
        labelVerificar2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 230, -1, -1));

        jLabel6.setText("Título:");
        labelVerificar2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 280, -1, -1));

        txtNombreProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProfesorActionPerformed(evt);
            }
        });
        labelVerificar2.add(txtNombreProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 40, 176, -1));
        labelVerificar2.add(txtApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 88, 176, -1));
        labelVerificar2.add(txtApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 136, 176, -1));
        labelVerificar2.add(txtIdProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 178, 176, -1));
        labelVerificar2.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 226, 176, -1));

        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });
        labelVerificar2.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 276, 180, -1));

        buttonModificarProfesor.setText("Modificar");
        buttonModificarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModificarProfesorActionPerformed(evt);
            }
        });
        labelVerificar2.add(buttonModificarProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 268, 84, -1));

        jLabel7.setText("Profesores");
        labelVerificar2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        cbxModificar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "Apellido paterno", "Apellido materno", "Correo", "ID", "Título" }));
        cbxModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxModificarActionPerformed(evt);
            }
        });
        labelVerificar2.add(cbxModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 268, 110, 32));

        obligatorio1.setText("Campo obligatorio.");
        labelVerificar2.add(obligatorio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 70, 158, -1));

        obligatorio2.setText("Campo obligatorio.");
        labelVerificar2.add(obligatorio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 118, 176, -1));

        obligatorio3.setText("Campo obligatorio.");
        labelVerificar2.add(obligatorio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 161, 176, -1));

        obligatorio4.setText("Campo obligatorio.");
        labelVerificar2.add(obligatorio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 204, 176, -1));

        obligatorio5.setText("Campo obligatorio.");
        labelVerificar2.add(obligatorio5, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 254, 176, -1));

        label6.setText(" ");
        labelVerificar2.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 306, -1, -1));

        obligatorio6.setText("Campo obligatorio.");
        labelVerificar2.add(obligatorio6, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 306, 167, -1));

        buttonAltas.setText("Altas y bajas");
        buttonAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAltasActionPerformed(evt);
            }
        });
        labelVerificar2.add(buttonAltas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 200, -1));

        labelVerificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1477903427_sign-check.png"))); // NOI18N
        labelVerificar2.add(labelVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, -1, 24));

        buttonAddProfesor.setText("Agregar profesor");
        buttonAddProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddProfesorActionPerformed(evt);
            }
        });
        labelVerificar2.add(buttonAddProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, -1, -1));

        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        labelVerificar2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 90, -1));

        labelVerificar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1477903427_sign-check.png"))); // NOI18N
        labelVerificar2.add(labelVerificar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, -1, -1));

        buttonEliminarProfesor.setText("Eliminar profesor");
        buttonEliminarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEliminarProfesorActionPerformed(evt);
            }
        });
        labelVerificar2.add(buttonEliminarProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, -1, -1));

        buttonGenID.setText("Generar ID");
        buttonGenID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGenIDActionPerformed(evt);
            }
        });
        labelVerificar2.add(buttonGenID, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondoVentana4.jpg"))); // NOI18N
        labelVerificar2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 570, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelVerificar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelVerificar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonEliminarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEliminarProfesorActionPerformed
        seleccionProf = listProfesor.getSelectedIndex();
        if (seleccionProf!=-1) {
            list_model.eliminarProfesor(seleccionProf);
        }
    }//GEN-LAST:event_buttonEliminarProfesorActionPerformed

//BOTON AGREGAR PROFESOR
    private void buttonAddProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddProfesorActionPerformed
        contador = 0;
        
       campoObligatorio(); // cada vez que falte un campo, se le sumara 1 al contador
       if(contador== 0){ // si ningun campo falta el contador valdra 0, entonces podra agregarse el profesor
            Profesor p = new Profesor(txtIdProfesor.getText(),txtNombreProfesor.getText(),txtApellidoPaterno.getText(), txtApellidoMaterno.getText(),
            txtCorreo.getText(),txtTitulo.getText());
            list_model.addProfesor(p);
         
              v.setM(v.getM());
            txtIdProfesor.setText("0024"+(v.getM()));
       }
    }//GEN-LAST:event_buttonAddProfesorActionPerformed

    private void buttonModificarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModificarProfesorActionPerformed
        int profSeleccion;
        int opcion;
        profSeleccion = listProfesor.getSelectedIndex(); //opcion seleccionada en el JList profesor
         opcion = cbxModificar.getSelectedIndex(); // opcion seleccionada en el ComboBox desplegable
        if (profSeleccion != -1){
        list_model.actualizarProfesor(opcion, profSeleccion);
        }
    }//GEN-LAST:event_buttonModificarProfesorActionPerformed

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void txtNombreProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProfesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProfesorActionPerformed

    private void buttonAltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAltasActionPerformed
       seleccionProf = listProfesor.getSelectedIndex();
        if (seleccionProf != -1){
        AltaProfesores alta = new AltaProfesores(seleccionProf, materias, list_model);
        alta.setVisible(true);
        }
    }//GEN-LAST:event_buttonAltasActionPerformed

    private void cbxModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxModificarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtNombreProfesor.setText(" "); txtApellidoPaterno.setText(" ");txtApellidoMaterno.setText(" "); txtCorreo.setText(" ");
        txtTitulo.setText(" ");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buttonGenIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGenIDActionPerformed
          txtIdProfesor.setText("0024"+(v.getM()));
    }//GEN-LAST:event_buttonGenIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerProfesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerProfesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerProfesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerProfesores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerProfesores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddProfesor;
    private javax.swing.JButton buttonAltas;
    private javax.swing.JButton buttonEliminarProfesor;
    private javax.swing.JButton buttonGenID;
    private javax.swing.JButton buttonModificarProfesor;
    private javax.swing.JComboBox<String> cbxModificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel labelVerificar;
    private javax.swing.JPanel labelVerificar2;
    private javax.swing.JLabel labelVerificar3;
    private javax.swing.JList<String> listProfesor;
    private javax.swing.JLabel obligatorio1;
    private javax.swing.JLabel obligatorio2;
    private javax.swing.JLabel obligatorio3;
    private javax.swing.JLabel obligatorio4;
    private javax.swing.JLabel obligatorio5;
    private javax.swing.JLabel obligatorio6;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtApellidoPaterno;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtIdProfesor;
    private javax.swing.JTextField txtNombreProfesor;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
